from app import app, db
from models import Doctor, Patient, Diagnosis, Medication
from werkzeug.security import generate_password_hash
import os

def seed():
    with app.app_context():
        # Make sure instance directory exists
        instance_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'instance')
        os.makedirs(instance_path, exist_ok=True)

        # Drop and recreate all tables
        db.drop_all()
        db.create_all()

        # Add doctor
        doctor = Doctor(username='doctor', password_hash=generate_password_hash('password'))
        db.session.add(doctor)

        # Add patients
        patients = [
            Patient(name='Ali Khan', father_name='Ahmed Khan', age=30, sex='Male', contact='03001234567'),
            Patient(name='Sara Ahmed', father_name='Imran Ahmed', age=25, sex='Female', contact='03007654321'),
            Patient(name='Bilal Raza', father_name='Rashid Raza', age=40, sex='Male', contact='03111234567'),
        ]
        db.session.add_all(patients)

        # Add diagnoses
        diagnoses = [
            Diagnosis(code='F01.0', description="Vascular dementia of acute onset"),
            Diagnosis(code='F01.1', description="Multi-infarct dementia"),
            Diagnosis(code='F01.2', description="Subcortical vascular dementia"),
            Diagnosis(code='F01.3', description="Mixed cortical and subcortical vascular dementia"),
            Diagnosis(code='F01.8', description="Other vascular dementia"),
            Diagnosis(code='F01.9', description="Vascular dementia, unspecified"),
            Diagnosis(code='F02.0', description="Dementia in Pick's disease"),
            Diagnosis(code='F02.1', description="Dementia in Creutzfeldt–Jakob disease"),
            Diagnosis(code='F02.2', description="Dementia in Huntington's disease"),
            Diagnosis(code='F02.3', description="Dementia in Parkinson's disease"),
            Diagnosis(code='F02.4', description="Dementia in HIV disease"),
            Diagnosis(code='F02.8', description="Dementia in other specified diseases classified elsewhere"),
            Diagnosis(code='F03', description="Unspecified dementia"),
            Diagnosis(code='F04', description="Organic amnesic syndrome, not induced by alcohol or other psychoactive substances"),
            Diagnosis(code='F05.0', description="Delirium not superimposed on dementia"),
            Diagnosis(code='F05.1', description="Delirium superimposed on dementia"),
            Diagnosis(code='F05.8', description="Other delirium"),
            Diagnosis(code='F05.9', description="Delirium, unspecified"),
            Diagnosis(code='F06.0', description="Organic hallucinosis"),
            Diagnosis(code='F06.1', description="Organic catatonic disorder"),
            Diagnosis(code='F06.2', description="Organic delusional [schizophrenia-like] disorder"),
            Diagnosis(code='F06.3', description="Organic mood [affective] disorders"),
            Diagnosis(code='F06.4', description="Organic anxiety disorder"),
            Diagnosis(code='F06.5', description="Organic dissociative disorder"),
            Diagnosis(code='F06.6', description="Organic emotionally labile [asthenic] disorder"),
            Diagnosis(code='F06.7', description="Mild cognitive disorder"),
            Diagnosis(code='F06.8', description="Other specified mental disorders due to brain damage and dysfunction and to physical disease"),
            Diagnosis(code='F06.9', description="Unspecified mental disorder due to brain damage and dysfunction and to physical disease"),
            Diagnosis(code='F07.0', description="Organic personality disorder"),
            Diagnosis(code='F07.1', description="Postencephalitic syndrome"),
            Diagnosis(code='F07.2', description="Postconcussional syndrome"),
            Diagnosis(code='F07.8', description="Other organic personality and behavioural disorders due to brain disease, damage and dysfunction"),
            Diagnosis(code='F07.9', description="Unspecified organic personality and behavioural disorder due to brain disease, damage and dysfunction"),
            Diagnosis(code='F09', description="Unspecified organic or symptomatic mental disorder"),
            Diagnosis(code='F10.0', description="Acute intoxication (alcohol)"),
            Diagnosis(code='F10.1', description="Harmful use (alcohol)"),
            Diagnosis(code='F10.2', description="Dependence syndrome (alcohol)"),
            Diagnosis(code='F10.3', description="Withdrawal state (alcohol)"),
            Diagnosis(code='F10.4', description="Withdrawal state with delirium"),
            Diagnosis(code='F10.5', description="Psychotic disorder (alcohol)"),
            Diagnosis(code='F10.6', description="Amnesic syndrome (alcohol)"),
            Diagnosis(code='F10.7', description="Residual and late-onset psychotic disorder (alcohol)"),
            Diagnosis(code='F10.8', description="Other mental and behavioural disorders due to alcohol"),
            Diagnosis(code='F10.9', description="Unspecified mental and behavioural disorder due to alcohol"),
            Diagnosis(code='F11.0', description="Acute intoxication (opioids)"),
            Diagnosis(code='F11.1', description="Harmful use (opioids)"),
            Diagnosis(code='F11.2', description="Dependence syndrome (opioids)"),
            Diagnosis(code='F11.3', description="Withdrawal state (opioids)"),
            Diagnosis(code='F11.4', description="Withdrawal state with delirium (opioids)"),
            Diagnosis(code='F11.5', description="Psychotic disorder (opioids)"),
            Diagnosis(code='F11.6', description="Amnesic syndrome (opioids)"),
            Diagnosis(code='F11.7', description="Residual and late-onset psychotic disorder (opioids)"),
            Diagnosis(code='F11.8', description="Other mental and behavioural disorders due to opioids"),
            Diagnosis(code='F11.9', description="Unspecified mental and behavioural disorder due to opioids"),
            Diagnosis(code='F20.0', description="Paranoid schizophrenia"),
            Diagnosis(code='F20.1', description="Hebephrenic schizophrenia"),
            Diagnosis(code='F20.2', description="Catatonic schizophrenia"),
            Diagnosis(code='F20.3', description="Undifferentiated schizophrenia"),
            Diagnosis(code='F20.4', description="Post‑schizophrenic depression"),
            Diagnosis(code='F20.5', description="Residual schizophrenia"),
            Diagnosis(code='F20.6', description="Simple schizophrenia"),
            Diagnosis(code='F20.8', description="Other schizophrenia"),
            Diagnosis(code='F20.9', description="Schizophrenia, unspecified"),
            Diagnosis(code='F21', description="Schizotypal disorder"),
            Diagnosis(code='F22.0', description="Delusional disorder"),
            Diagnosis(code='F22.8', description="Other persistent delusional disorders"),
            Diagnosis(code='F22.9', description="Persistent delusional disorder, unspecified"),
            Diagnosis(code='F23.0', description="Acute polymorphic psychotic disorder without symptoms of schizophrenia"),
            Diagnosis(code='F23.1', description="Acute polymorphic psychotic disorder with symptoms of schizophrenia"),
            Diagnosis(code='F23.2', description="Acute schizophrenia-like psychotic disorder"),
            Diagnosis(code='F23.3', description="Other acute predominantly delusional psychotic disorders"),
            Diagnosis(code='F23.8', description="Other acute and transient psychotic disorders"),
            Diagnosis(code='F23.9', description="Acute and transient psychotic disorder, unspecified"),
            Diagnosis(code='F24', description="Induced delusional (shared) disorder"),
            Diagnosis(code='F25.0', description="Schizoaffective disorder, manic type"),
            Diagnosis(code='F25.1', description="Schizoaffective disorder, depressive type"),
            Diagnosis(code='F25.2', description="Schizoaffective disorder, mixed type"),
            Diagnosis(code='F25.8', description="Other schizoaffective disorders"),
            Diagnosis(code='F25.9', description="Schizoaffective disorder, unspecified"),
            Diagnosis(code='F28', description="Other nonorganic psychotic disorders"),
            Diagnosis(code='F29', description="Unspecified nonorganic psychosis"),
            Diagnosis(code='F30.0', description="Hypomania"),
            Diagnosis(code='F30.1', description="Mania without psychotic symptoms"),
            Diagnosis(code='F30.2', description="Mania with psychotic symptoms"),
            Diagnosis(code='F30.8', description="Other manic episode"),
            Diagnosis(code='F30.9', description="Manic episode, unspecified"),
            Diagnosis(code='F31.0', description="Current episode hypomanic (bipolar)"),
            Diagnosis(code='F31.1', description="Current episode manic without psychotic symptoms"),
            Diagnosis(code='F31.2', description="Current episode manic with psychotic symptoms"),
            Diagnosis(code='F31.3', description="Current episode mild or moderate depression"),
            Diagnosis(code='F31.4', description="Current episode severe depression without psychotic symptoms"),
            Diagnosis(code='F31.5', description="Current episode severe depression with psychotic symptoms"),
            Diagnosis(code='F31.6', description="Currently in remission"),
            Diagnosis(code='F31.7', description="Other bipolar disorders"),
            Diagnosis(code='F31.8', description="Bipolar disorder, other and unspecified"),
            Diagnosis(code='F32.0', description="Mild depressive episode"),
            Diagnosis(code='F32.1', description="Moderate depressive episode"),
            Diagnosis(code='F32.2', description="Severe depressive episode without psychotic symptoms"),
            Diagnosis(code='F32.3', description="Severe depressive episode with psychotic symptoms"),
            Diagnosis(code='F32.8', description="Other depressive episode"),
            Diagnosis(code='F32.9', description="Depressive episode, unspecified"),
            Diagnosis(code='F33.0', description="Recurrent depressive disorder, current episode mild"),
            Diagnosis(code='F33.1', description="Recurrent depressive disorder, current episode moderate"),
            Diagnosis(code='F33.2', description="Recurrent depressive disorder, current episode severe without psychotic symptoms"),
            Diagnosis(code='F33.3', description="Recurrent depressive disorder, current episode severe with psychotic symptoms"),
            Diagnosis(code='F33.4', description="Recurrent depressive disorder, currently in remission"),
            Diagnosis(code='F33.8', description="Other recurrent depressive disorders"),
            Diagnosis(code='F33.9', description="Recurrent depressive disorder, unspecified"),
            Diagnosis(code='F34.0', description="Cyclothymia"),
            Diagnosis(code='F34.1', description="Dysthymia"),
            Diagnosis(code='F34.8', description="Other persistent mood disorders"),
            Diagnosis(code='F34.9', description="Persistent mood disorder, unspecified"),
            Diagnosis(code='F38.0', description="Mixed single mood disorder"),
            Diagnosis(code='F38.1', description="Other recurrent mood disorders"),
            Diagnosis(code='F38.8', description="Other specified mood disorders"),
            Diagnosis(code='F39', description="Mood disorder, unspecified"),
            Diagnosis(code='F40.0', description="Agoraphobia without panic disorder"),
            Diagnosis(code='F40.1', description="Social phobia"),
            Diagnosis(code='F40.2', description="Specific phobia"),
            Diagnosis(code='F40.8', description="Other phobic anxiety disorders"),
            Diagnosis(code='F40.9', description="Phobic anxiety disorder, unspecified"),
            Diagnosis(code='F41.0', description="Panic disorder"),
            Diagnosis(code='F41.1', description="Generalized anxiety disorder"),
            Diagnosis(code='F41.2', description="Mixed anxiety and depressive disorder"),
            Diagnosis(code='F41.3', description="Other mixed anxiety disorders"),
            Diagnosis(code='F41.8', description="Other specified anxiety disorders"),
            Diagnosis(code='F41.9', description="Anxiety disorder, unspecified"),
            Diagnosis(code='F42.0', description="Predominantly obsessional thoughts"),
            Diagnosis(code='F42.1', description="Predominantly compulsive acts"),
            Diagnosis(code='F42.2', description="Mixed obsessional thoughts and acts"),
            Diagnosis(code='F42.8', description="Other obsessive–compulsive disorders"),
            Diagnosis(code='F42.9', description="Obsessive–compulsive disorder, unspecified"),
            Diagnosis(code='F43.0', description="Acute stress reaction"),
            Diagnosis(code='F43.1', description="Post‑traumatic stress disorder"),
            Diagnosis(code='F43.2', description="Adjustment disorders"),
            Diagnosis(code='F43.8', description="Other reactions to severe stress"),
            Diagnosis(code='F43.9', description="Reaction to severe stress, unspecified"),
            Diagnosis(code='F44.0', description="Dissociative amnesia"),
            Diagnosis(code='F44.1', description="Dissociative fugue"),
            Diagnosis(code='F44.2', description="Dissociative stupor"),
            Diagnosis(code='F44.3', description="Trance and possession disorders"),
            Diagnosis(code='F44.4', description="Dissociative motor disorders"),
            Diagnosis(code='F44.5', description="Dissociative convulsions"),
            Diagnosis(code='F44.6', description="Dissociative anesthesia and sensory loss"),
            Diagnosis(code='F44.7', description="Mixed dissociative disorders"),
            Diagnosis(code='F44.8', description="Other dissociative disorders"),
            Diagnosis(code='F44.9', description="Dissociative disorder, unspecified"),
            Diagnosis(code='F45.0', description="Somatization disorder"),
            Diagnosis(code='F45.1', description="Undifferentiated somatoform disorder"),
            Diagnosis(code='F45.2', description="Hypochondriacal disorder"),
            Diagnosis(code='F45.3', description="Somatoform autonomic dysfunction"),
            Diagnosis(code='F45.4', description="Persistent somatoform pain disorder"),
            Diagnosis(code='F45.8', description="Other somatoform disorders"),
            Diagnosis(code='F45.9', description="Somatoform disorder, unspecified"),
            Diagnosis(code='F48.0', description="Neurasthenia"),
            Diagnosis(code='F48.1', description="Depersonalization–derealization syndrome"),
            Diagnosis(code='F48.8', description="Other specified neurotic disorders"),
            Diagnosis(code='F48.9', description="Neurotic disorder, unspecified"),
            Diagnosis(code='F50.0', description="Anorexia nervosa"),
            Diagnosis(code='F50.1', description="Atypical anorexia nervosa"),
            Diagnosis(code='F50.2', description="Bulimia nervosa"),
            Diagnosis(code='F50.3', description="Atypical bulimia nervosa"),
            Diagnosis(code='F50.4', description="Overeating associated with other psychological disturbances"),
            Diagnosis(code='F50.5', description="Vomiting associated with other psychological disturbances"),
            Diagnosis(code='F50.8', description="Other eating disorders"),
            Diagnosis(code='F50.9', description="Eating disorder, unspecified"),
            Diagnosis(code='F51.0', description="Nonorganic insomnia"),
            Diagnosis(code='F51.1', description="Nonorganic hypersomnia"),
            Diagnosis(code='F51.2', description="Disorder of the sleep-wake schedule"),
            Diagnosis(code='F51.3', description="Sleepwalking"),
            Diagnosis(code='F51.4', description="Sleep terrors"),
            Diagnosis(code='F51.5', description="Nightmares"),
            Diagnosis(code='F51.8', description="Other nonorganic sleep disorders"),
            Diagnosis(code='F51.9', description="Nonorganic sleep disorder, unspecified"),
            Diagnosis(code='F52.0', description="Lack or loss of sexual desire"),
            Diagnosis(code='F52.1', description="Sexual aversion and lack of enjoyment"),
            Diagnosis(code='F52.2', description="Failure of genital response"),
            Diagnosis(code='F52.3', description="Orgasmic dysfunction"),
            Diagnosis(code='F52.4', description="Premature ejaculation"),
            Diagnosis(code='F52.5', description="Nonorganic vaginismus"),
            Diagnosis(code='F52.6', description="Nonorganic dyspareunia"),
            Diagnosis(code='F52.7', description="Excessive sexual drive"),
            Diagnosis(code='F52.8', description="Other sexual dysfunction"),
            Diagnosis(code='F52.9', description="Sexual dysfunction, unspecified"),
            Diagnosis(code='F53.0', description="Mild mental and behavioural disorders associated with puerperium"),
            Diagnosis(code='F53.1', description="Severe mental and behavioural disorders associated with puerperium"),
            Diagnosis(code='F53.8', description="Other mental and behavioural disorders associated with puerperium"),
            Diagnosis(code='F53.9', description="Puerperal mental disorder, unspecified"),
            Diagnosis(code='F54', description="Psychological and behavioural factors associated with disorders or diseases classified elsewhere"),
            Diagnosis(code='F55.0', description="Abuse of antidepressants"),
            Diagnosis(code='F55.1', description="Abuse of laxatives"),
            Diagnosis(code='F55.2', description="Abuse of analgesics"),
            Diagnosis(code='F55.3', description="Abuse of antacids"),
            Diagnosis(code='F55.4', description="Abuse of vitamins"),
            Diagnosis(code='F55.5', description="Abuse of steroids or hormones"),
            Diagnosis(code='F55.6', description="Abuse of specific herbal or folk remedies"),
            Diagnosis(code='F55.8', description="Abuse of other non-dependence producing substances"),
            Diagnosis(code='F55.9', description="Abuse of unspecified non-dependence producing substance"),
            Diagnosis(code='F59', description="Unspecified behavioural syndrome"),
            Diagnosis(code='F60.0', description="Paranoid personality disorder"),
            Diagnosis(code='F60.1', description="Schizoid personality disorder"),
            Diagnosis(code='F60.2', description="Dissocial personality disorder"),
            Diagnosis(code='F60.3', description="Emotionally unstable personality disorder – impulsive type"),
            Diagnosis(code='F60.31', description="Emotionally unstable personality disorder – borderline type"),
            Diagnosis(code='F60.4', description="Histrionic personality disorder"),
            Diagnosis(code='F60.5', description="Anankastic (obsessive–compulsive) personality disorder"),
            Diagnosis(code='F60.6', description="Anxious (avoidant) personality disorder"),
            Diagnosis(code='F60.7', description="Dependent personality disorder"),
            Diagnosis(code='F60.8', description="Other specific personality disorders"),
            Diagnosis(code='F60.9', description="Personality disorder, unspecified"),
            Diagnosis(code='F61.0', description="Mixed personality disorders"),
            Diagnosis(code='F61.1', description="Troublesome personality changes"),
            Diagnosis(code='F62.0', description="Enduring personality change after catastrophic experience"),
            Diagnosis(code='F62.1', description="Enduring personality change after psychiatric illness"),
            Diagnosis(code='F62.8', description="Other enduring personality changes"),
            Diagnosis(code='F62.9', description="Enduring personality change, unspecified"),
            Diagnosis(code='F63.0', description="Pathological gambling"),
            Diagnosis(code='F63.1', description="Pathological fire‑setting [pyromania]"),
            Diagnosis(code='F63.2', description="Pathological stealing [kleptomania]"),
            Diagnosis(code='F63.3', description="Trichotillomania"),
            Diagnosis(code='F63.8', description="Other habit and impulse disorders"),
            Diagnosis(code='F63.9', description="Impulse disorder, unspecified"),
            Diagnosis(code='F64.0', description="Transsexualism"),
            Diagnosis(code='F64.1', description="Dual-role transvestism"),
            Diagnosis(code='F64.2', description="Gender identity disorder of childhood"),
            Diagnosis(code='F64.8', description="Other gender identity disorders"),
            Diagnosis(code='F64.9', description="Gender identity disorder, unspecified"),
            Diagnosis(code='F65.0', description="Fetishism"),
            Diagnosis(code='F65.1', description="Fetishistic transvestism"),
            Diagnosis(code='F65.2', description="Exhibitionism"),
            Diagnosis(code='F65.3', description="Voyeurism"),
            Diagnosis(code='F65.4', description="Paedophilia"),
            Diagnosis(code='F65.5', description="Sadomasochism"),
            Diagnosis(code='F65.6', description="Multiple disorders of sexual preference"),
            Diagnosis(code='F65.8', description="Other disorders of sexual preference"),
            Diagnosis(code='F65.9', description="Disorder of sexual preference, unspecified"),
            Diagnosis(code='F66.0', description="Sexual maturation disorder"),
            Diagnosis(code='F66.1', description="Egodystonic sexual orientation"),
            Diagnosis(code='F66.2', description="Sexual relationship disorder"),
            Diagnosis(code='F66.8', description="Other psychosexual development disorders"),
            Diagnosis(code='F66.9', description="Psychosexual development disorder, unspecified"),
            Diagnosis(code='F68.0', description="Elaboration of physical symptoms for psychological reasons"),
            Diagnosis(code='F68.1', description="Intentional production or feigning of symptoms [factitious disorder]"),
            Diagnosis(code='F68.8', description="Other specified disorders of adult personality and behaviour"),
            Diagnosis(code='F69', description="Unspecified adult personality and behavioural disorder"),
            Diagnosis(code='F70', description="Mild intellectual disability"),
            Diagnosis(code='F71', description="Moderate intellectual disability"),
            Diagnosis(code='F72', description="Severe intellectual disability"),
            Diagnosis(code='F73', description="Profound intellectual disability"),
            Diagnosis(code='F78', description="Other intellectual disability"),
            Diagnosis(code='F79', description="Intellectual disability, unspecified"),
            Diagnosis(code='F80.0', description="Specific speech articulation disorder"),
            Diagnosis(code='F80.1', description="Expressive language disorder"),
            Diagnosis(code='F80.2', description="Receptive language disorder"),
            Diagnosis(code='F80.3', description="Acquired aphasia with epilepsy [Landau–Kleffner syndrome]"),
            Diagnosis(code='F80.8', description="Other developmental disorders of speech and language"),
            Diagnosis(code='F80.9', description="Developmental disorder of speech and language, unspecified"),
            Diagnosis(code='F81.0', description="Specific reading disorder"),
            Diagnosis(code='F81.1', description="Specific spelling disorder"),
            Diagnosis(code='F81.2', description="Specific arithmetical disorder"),
            Diagnosis(code='F81.3', description="Mixed disorder of scholastic skills"),
            Diagnosis(code='F81.8', description="Other developmental disorders of scholastic skills"),
            Diagnosis(code='F81.9', description="Developmental disorder of scholastic skills, unspecified"),
            Diagnosis(code='F82', description="Specific developmental disorder of motor function"),
            Diagnosis(code='F83', description="Mixed developmental disorders"),
            Diagnosis(code='F84.0', description="Childhood autism"),
            Diagnosis(code='F84.1', description="Atypical autism"),
            Diagnosis(code='F84.2', description="Rett’s syndrome"),
            Diagnosis(code='F84.3', description="Other childhood disintegrative disorder"),
            Diagnosis(code='F84.4', description="Overactive disorder associated with intellectual disability and stereotyped movements"),
            Diagnosis(code='F84.5', description="Asperger’s syndrome"),
            Diagnosis(code='F84.8', description="Other pervasive developmental disorders"),
            Diagnosis(code='F84.9', description="Pervasive developmental disorder, unspecified"),
            Diagnosis(code='F88', description="Other disorders of psychological development"),
            Diagnosis(code='F89', description="Psychological development disorder, unspecified"),
            Diagnosis(code='F90.0', description="Disturbance of activity and attention (ADHD)"),
            Diagnosis(code='F90.1', description="Hyperkinetic conduct disorder"),
            Diagnosis(code='F90.8', description="Other hyperkinetic disorders"),
            Diagnosis(code='F90.9', description="Hyperkinetic disorder, unspecified"),
            Diagnosis(code='F91.0', description="Conduct disorder confined to family context"),
            Diagnosis(code='F91.1', description="Unsocialized conduct disorder"),
            Diagnosis(code='F91.2', description="Socialized conduct disorder"),
            Diagnosis(code='F91.3', description="Oppositional defiant disorder"),
            Diagnosis(code='F91.8', description="Other conduct disorders"),
            Diagnosis(code='F91.9', description="Conduct disorder, unspecified"),
            Diagnosis(code='F92.0', description="Depressive conduct disorder"),
            Diagnosis(code='F92.8', description="Other mixed conduct and emotional disorders"),
            Diagnosis(code='F92.9', description="Mixed conduct and emotional disorder, unspecified"),
            Diagnosis(code='F93.0', description="Separation anxiety disorder of childhood"),
            Diagnosis(code='F93.1', description="Phobic anxiety disorder of childhood"),
            Diagnosis(code='F93.2', description="Social anxiety disorder of childhood"),
            Diagnosis(code='F93.3', description="Sibling rivalry disorder"),
            Diagnosis(code='F93.8', description="Other emotional disorders of childhood"),
            Diagnosis(code='F93.9', description="Childhood emotional disorder, unspecified"),
            Diagnosis(code='F94.0', description="Elective mutism"),
            Diagnosis(code='F94.1', description="Reactive attachment disorder of childhood"),
            Diagnosis(code='F94.2', description="Disinhibited attachment disorder of childhood"),
            Diagnosis(code='F94.8', description="Other childhood disorders of social functioning"),
            Diagnosis(code='F94.9', description="Childhood disorders of social functioning, unspecified"),
            Diagnosis(code='F95.0', description="Transient tic disorder"),
            Diagnosis(code='F95.1', description="Chronic motor or vocal tic disorder"),
            Diagnosis(code='F95.2', description="Combined vocal and multiple motor tic disorder [Tourette’s]"),
            Diagnosis(code='F95.8', description="Other tic disorders"),
            Diagnosis(code='F95.9', description="Tic disorder, unspecified"),
            Diagnosis(code='F98.0', description="Nonorganic enuresis"),
            Diagnosis(code='F98.1', description="Nonorganic encopresis"),
            Diagnosis(code='F98.2', description="Feeding disorder of infancy and childhood"),
            Diagnosis(code='F98.3', description="Pica of infancy and childhood"),
            Diagnosis(code='F98.4', description="Stereotyped movement disorders"),
            Diagnosis(code='F98.5', description="Stuttering"),
            Diagnosis(code='F98.6', description="Cluttering"),
            Diagnosis(code='F98.8', description="Other specified behavioural and emotional disorders with onset usually in childhood and adolescence"),
            Diagnosis(code='F98.9', description="Behavioural and emotional disorder, unspecified with onset usually occurring in childhood and adolescence"),
            Diagnosis(code='F99', description="Mental disorder, not otherwise specified"),
        ]
        db.session.add_all(diagnoses)

        # Add medications
        medications = [
            Medication(name='Abilify'),
            Medication(name='Abilify Maintena'),
            Medication(name='agomelatine'),
            Medication(name='Alaquet'),
            Medication(name='Allegron'),
            Medication(name='alprazolam'),
            Medication(name='Alventa XL'),
            Medication(name='Alzain'),
            Medication(name='amisulpride'),
            Medication(name='amitriptyline'),
            Medication(name='Amphero XL'),
            Medication(name='Anquil'),
            Medication(name='aripiprazole'),
            Medication(name='Arpoya'),
            Medication(name='asenapine'),
            Medication(name='Ativan'),
            Medication(name='Atrolak'),
            Medication(name='Axalid'),
            Medication(name='benperidol'),
            Medication(name='Biquelle'),
            Medication(name='Brancico'),
            Medication(name='Brintellix'),
            Medication(name='buspirone'),
            Medication(name='Camcolit'),
            Medication(name='Carbagen'),
            Medication(name='carbamazepine'),
            Medication(name='cariprazine'),
            Medication(name='Chloractil'),
            Medication(name='chloral hydrate'),
            Medication(name='chlordiazepoxide'),
            Medication(name='chlorpromazine'),
            Medication(name='cloral betaine'),
            Medication(name='Cipralex'),
            Medication(name='Cipramil'),
            Medication(name='Circadin'),
            Medication(name='citalopram'),
            Medication(name='clomethiazole'),
            Medication(name='clomipramine'),
            Medication(name='Clopixol'),
            Medication(name='Clopixol Acuphase'),
            Medication(name='Clopixol Concentrate'),
            Medication(name='clozapine'),
            Medication(name='Clozaril'),
            Medication(name='Cymbalta'),
            Medication(name='Denzapine'),
            Medication(name='Depakote'),
            Medication(name='Depefex XL'),
            Medication(name='Depixol'),
            Medication(name='Diazemuls'),
            Medication(name='diazepam'),
            Medication(name='Diazepam RecTubes'),
            Medication(name='diphenhydramine'),
            Medication(name='Dolmatil'),
            Medication(name='Dormagen'),
            Medication(name='dosulepin'),
            Medication(name='doxepin'),
            Medication(name='duloxetine'),
            Medication(name='Ebesque'),
            Medication(name='Edronax'),
            Medication(name='Efexor XL'),
            Medication(name='Epilim'),
            Medication(name='escitalopram'),
            Medication(name='Faverin'),
            Medication(name='Fluanxol'),
            Medication(name='fluoxetine'),
            Medication(name='flupentixol'),
            Medication(name='flupentixol decanoate'),
            Medication(name='fluphenazine decanoate'),
            Medication(name='fluvoxamine'),
            Medication(name='Foraven XL'),
            Medication(name='Haldol'),
            Medication(name='Haldol decanoate'),
            Medication(name='Halkid'),
            Medication(name='haloperidol'),
            Medication(name='haloperidol decanoate'),
            Medication(name='Heminevrin'),
            Medication(name='imipramine'),
            Medication(name='Invega'),
            Medication(name='isocarboxazid'),
            Medication(name='Lamictal'),
            Medication(name='lamotrigine'),
            Medication(name='Largactil'),
            Medication(name='Latuda'),
            Medication(name='Lecaent'),
            Medication(name='levomepromazine'),
            Medication(name='Li-liquid'),
            Medication(name='Librium'),
            Medication(name='Liskonum'),
            Medication(name='lithium carbonate'),
            Medication(name='lithium citrate'),
            Medication(name='lofepramine'),
            Medication(name='Lomont'),
            Medication(name='loprazolam'),
            Medication(name='lorazepam'),
            Medication(name='lormetazepam'),
            Medication(name='lurasidone'),
            Medication(name='Lustral'),
            Medication(name='Lyrica'),
            Medication(name='Majoven XL'),
            Medication(name='Manerix'),
            Medication(name='melatonin'),
            Medication(name='mianserin'),
            Medication(name='Mintreleg'),
            Medication(name='mirtazapine'),
            Medication(name='moclobemide'),
            Medication(name='Modecate'),
            Medication(name='Mogadon'),
            Medication(name='Molipaxin'),
            Medication(name='Nardil'),
            Medication(name='Neulactil'),
            Medication(name='nitrazepam'),
            Medication(name='nortriptyline'),
            Medication(name='Nozinan'),
            Medication(name='olanzapine'),
            Medication(name='olanzapine pamoate monohydrate'),
            Medication(name='Olena'),
            Medication(name='Orap'),
            Medication(name='Oxactin'),
            Medication(name='oxazepam'),
            Medication(name='paliperidone'),
            Medication(name='paliperidone palmitate'),
            Medication(name='Parnate'),
            Medication(name='paroxetine'),
            Medication(name='pericyazine'),
            Medication(name='phenelzine'),
            Medication(name='Phenergan'),
            Medication(name='pimozide'),
            Medication(name='Politid XL'),
            Medication(name='pregabalin'),
            Medication(name='Priadel'),
            Medication(name='prochlorperazine'),
            Medication(name='promazine'),
            Medication(name='promethazine'),
            Medication(name='Prothiaden'),
            Medication(name='Prozac'),
            Medication(name='Prozep'),
            Medication(name='Psytoxil'),
            Medication(name='quetiapine'),
            Medication(name='Reagila'),
            Medication(name='reboxetine'),
            Medication(name='Risperdal'),
            Medication(name='Risperdal Consta'),
            Medication(name='risperidone'),
            Medication(name='Seroquel'),
            Medication(name='Seroxat'),
            Medication(name='sertraline'),
            Medication(name='Sinepin'),
            Medication(name='Slenyto'),
            Medication(name='Solian'),
            Medication(name='Sominex'),
            Medication(name='Stelazine'),
            Medication(name='Stemetil'),
            Medication(name='Stesolid'),
            Medication(name='Stilnoct'),
            Medication(name='sulpiride'),
            Medication(name='Sulpor'),
            Medication(name='Sunveniz XL'),
            Medication(name='Surmontil'),
            Medication(name='Sycrest'),
            Medication(name='Syncrodin'),
            Medication(name='Tegretol'),
            Medication(name='temazepam'),
            Medication(name='Tenprolide'),
            Medication(name='Tensium'),
            Medication(name='tranylcypromine'),
            Medication(name='trazodone'),
            Medication(name='Trevicta'),
            Medication(name='trifluoperazine'),
            Medication(name='trimipramine'),
            Medication(name='Tropium'),
            Medication(name='Valdoxan'),
            Medication(name='valproate'),
            Medication(name='Venaxx XL'),
            Medication(name='Venlablue XL'),
            Medication(name='Venladex XL'),
            Medication(name='venlafaxine'),
            Medication(name='Venlalic XL'),
            Medication(name='Venlasoz XL'),
            Medication(name='Vensir XL'),
            Medication(name='Venzip XL'),
            Medication(name='ViePax'),
            Medication(name='vortioxetine'),
            Medication(name='Welldorm'),
            Medication(name='Xanax'),
            Medication(name='Xeplion'),
            Medication(name='Zalasta'),
            Medication(name='Zaluron'),
            Medication(name='Zaponex'),
            Medication(name='Zimovane'),
            Medication(name='Zispin'),
            Medication(name='zolpidem'),
            Medication(name='zopiclone'),
            Medication(name='zuclopenthixol'),
            Medication(name='zuclopenthixol decanoate'),
            Medication(name='zuclopenthixol dihydrochloride'),
            Medication(name='ZypAdhera'),
            Medication(name='Zyprexa'),
        ]
        db.session.add_all(medications)

        db.session.commit()
        print('Database seeded successfully.')

if __name__ == '__main__':
    seed() 